import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import HeroInputsBook from "../components/HeroInputsBook";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="bg-no-repeat bg-hero h-hero rounded-2xl relative  lg:mx-auto lg:w-[1380px] lg:mt-[30px] ">
          <Header />
          <div className="pt-14">
            <h1 className="text-5xl text-center text-white font-bold">
              Helping Others
            </h1>
            <h1 className="text-[80px] text-center text-white  font-bold">
              Live & Travel
            </h1>
            <p className="text-center text-xl text-white font-semibold">
              Special offers to suit your plan
            </p>
          </div>
          <HeroInputsBook />
          {/* ?plan your trip */}
        </div>

        <div className="mt-[245px]">
          <div className="flex  flex-col lg:flex-row w-[324px]">
            <h1 className="text-3xl font-semibold">Plan your perfect trip</h1>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
