import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="bg-no-repeat bg-hero h-hero rounded-2xl  lg:mx-auto lg:w-[1380px] lg:mt-[30px] "></div>
      </main>
    </div>
  );
};

export default Home;
